package rslp

type ruletype int

const (
	Plural ruletype = iota + 1
	Advérbio
	Feminino
	Aumentantivo
	Substantivo
	Verbo
	Vogal
)

type Rule struct {
	Name        ruletype
	MinWordSize int
	WithSuffix  bool
	Suffixes    []string
	SubRules    []SubRule
}

type SubRule struct {
	Suffix     string
	StemSize   int
	Replace    string
	Exceptions []string
}

var defaultDictionary = []Rule{
	{
		Name:        Plural,
		MinWordSize: 3,
		WithSuffix:  false,
		Suffixes:    []string{"s"},
		SubRules: []SubRule{
			{"ns", 1, "m", nil},
			{"ões", 2, "ão", nil},
			{"ães", 1, "ão", []string{"mães"}},
			{"ais", 1, "al", []string{"cais", "mais"}},
			{"éis", 2, "el", nil},
			{"eis", 2, "el", nil},
			{"óis", 2, "ol", nil},
			{"is", 2, "il", []string{
				"lápis", "cais", "mais", "crúcis", "biquínis", "pois", "depois", "dois", "leis",
			}},
			{"les", 2, "l", nil},
			{"res", 2, "r", []string{"árvores"}},
			{"s", 2, "", []string{
				"aliás", "pires", "lápis", "cais", "mais", "mas", "menos", "férias", "fezes", "pêsames",
				"crúcis", "gás", "atrás", "moisés", "através", "convés", "ês", "país", "após", "ambas",
				"ambos", "messias", "depois",
			}},
		},
	},
	{
		Name:        Advérbio,
		MinWordSize: 0,
		WithSuffix:  false,
		Suffixes:    nil,
		SubRules: []SubRule{
			{"mente", 4, "", []string{"experimente"}},
		},
	},
	{
		Name:        Feminino,
		MinWordSize: 3,
		WithSuffix:  false,
		Suffixes:    []string{"a", "ã"},
		SubRules: []SubRule{
			{"ona", 3, "ão", []string{
				"abandona", "lona", "iona", "cortisona", "monótona", "maratona", "acetona", "detona", "carona",
			}},
			{"ora", 3, "or", nil},
			{"na", 4, "no", []string{
				"carona", "abandona", "lona", "iona", "cortisona", "monótona", "maratona", "acetona", "detona",
				"guiana", "campana", "grana", "caravana", "banana", "paisana",
			}},
			{"inha", 3, "inho", []string{"rainha", "linha", "minha"}},
			{"esa", 3, "ês", []string{"mesa", "obesa", "princesa", "turquesa", "ilesa", "pesa", "presa"}},
			{"osa", 3, "oso", []string{"mucosa", "prosa"}},
			{"íaca", 3, "íaco", nil},
			{"ica", 3, "ico", []string{"dica"}},
			{"ada", 2, "ado", []string{"pitada"}},
			{"ida", 3, "ido", []string{"vida", "dúvida"}},
			{"ída", 3, "ido", []string{"recaída", "saída"}},
			{"ima", 3, "imo", []string{"vítima"}},
			{"iva", 3, "ivo", []string{"saliva", "oliva"}},
			{"eira", 3, "eiro", []string{
				"beira", "cadeira", "frigideira", "bandeira", "feira", "capoeira", "barreira", "fronteira",
				"besteira", "poeira",
			}},
			{"ã", 2, "ão", []string{"amanhã", "arapuã", "fã", "divã"}},
		},
	},
	{
		Name:        Aumentantivo,
		MinWordSize: 0,
		WithSuffix:  false,
		Suffixes:    nil,
		SubRules: []SubRule{
			{"díssimo", 5, "", nil},
			{"abilíssimo", 5, "", nil},
			{"íssimo", 3, "", nil},
			{"ésimo", 3, "", nil},
			{"érrimo", 4, "", nil},
			{"zinho", 2, "", nil},
			{"quinho", 4, "c", nil},
			{"uinho", 4, "", nil},
			{"adinho", 3, "", nil},
			{"inho", 3, "", []string{"caminho", "cominho"}},
			{"alhão", 4, "", nil},
			{"uça", 4, "", nil},
			{"aço", 4, "", []string{"antebraço"}},
			{"aça", 4, "", nil},
			{"adão", 4, "", nil},
			{"idão", 4, "", nil},
			{"ázio", 3, "", []string{"topázio"}},
			{"arraz", 4, "", nil},
			{"zarrão", 3, "", nil},
			{"arrão", 4, "", nil},
			{"arra", 3, "", nil},
			{"zão", 2, "", []string{"coalizão"}},
			{"ão", 3, "", []string{
				"camarão", "chimarrão", "canção", "coração", "embrião", "grotão", "glutão", "ficção", "fogão",
				"feição", "furacão", "gamão", "lampião", "leão", "macacão", "nação", "órfão", "orgão", "patrão",
				"portão", "quinhão", "rincão", "tração", "falcão", "espião", "mamão", "folião", "cordão", "aptidão",
				"campeão", "colchão", "limão", "leilão", "melão", "barão", "milhão", "bilhão", "fusão", "cristão",
				"ilusão", "estação", "senão", "balão",
			}},
		},
	},
	{
		Name:        Substantivo,
		MinWordSize: 0,
		WithSuffix:  false,
		Suffixes:    nil,
		SubRules: []SubRule{
			{"encialista", 4, "", nil},
			{"alista", 5, "", nil},
			{"agem", 3, "", []string{"coragem", "chantagem", "vantagem", "carruagem"}},
			{"iamento", 4, "", nil},
			{"amento", 3, "", []string{"firmamento", "fundamento", "departamento"}},
			{"imento", 3, "", nil},
			{"mento", 6, "", []string{"firmamento", "elemento", "complemento", "instrumento", "departamento"}},
			{"alizado", 4, "", nil},
			{"atizado", 4, "", nil},
			{"tizado", 4, "", []string{"alfabetizado"}},
			{"izado", 5, "", []string{"organizado", "pulverizado"}},
			{"ativo", 4, "", []string{"pejorativo", "relativo"}},
			{"tivo", 4, "", []string{"relativo"}},
			{"ivo", 4, "", []string{"passivo", "possessivo", "pejorativo", "positivo"}},
			{"ado", 2, "", []string{"grado"}},
			{"ido", 3, "", []string{"cândido", "consolido", "rápido", "decido", "tímido", "duvido", "marido"}},
			{"ador", 3, "", nil},
			{"edor", 3, "", nil},
			{"idor", 4, "", []string{"ouvidor"}},
			{"dor", 4, "", []string{"ouvidor"}},
			{"sor", 4, "", []string{"assessor"}},
			{"atoria", 5, "", nil},
			{"tor", 3, "", []string{"benfeitor", "leitor", "editor", "pastor", "produtor", "promotor", "consultor"}},
			{"or", 2, "", []string{
				"motor", "melhor", "redor", "rigor", "sensor", "tambor", "tumor", "assessor",
				"benfeitor", "pastor", "terior", "favor", "autor",
			}},
			{"abilidade", 5, "", nil},
			{"icionista", 4, "", nil},
			{"cionista", 5, "", nil},
			{"ionista", 5, "", nil},
			{"ionar", 5, "", nil},
			{"ional", 4, "", nil},
			{"ência", 3, "", nil},
			{"ância", 4, "", []string{"ambulância"}},
			{"edouro", 3, "", nil},
			{"queiro", 3, "c", nil},
			{"adeiro", 4, "", []string{"desfiladeiro"}},
			{"eiro", 3, "", []string{"desfiladeiro", "pioneiro", "mosteiro"}},
			{"uoso", 3, "", nil},
			{"oso", 3, "", []string{"precioso"}},
			{"alizaç", 5, "", nil},
			{"atizaç", 5, "", nil},
			{"tizaç", 5, "", nil},
			{"izaç", 5, "", []string{"organizaç"}},
			{"aç", 3, "", []string{"equaç", "relaç"}},
			{"iç", 3, "", []string{"eleiç"}},
			{"ário", 3, "", []string{"voluntário", "salário", "aniversário", "diário", "lionário", "armário"}},
			{"atório", 3, "", nil},
			{"rio", 5, "", []string{
				"voluntário", "salário", "aniversário", "diário", "compulsório", "lionário",
				"próprio", "stério", "armário",
			}},
			{"ério", 6, "", nil},
			{"ês", 4, "", nil},
			{"eza", 3, "", nil},
			{"ez", 4, "", nil},
			{"esco", 4, "", nil},
			{"ante", 2, "", []string{"gigante", "elefante", "adiante", "possante", "instante", "restaurante"}},
			{"ástico", 4, "", []string{"eclesiástico"}},
			{"alístico", 3, "", nil},
			{"áutico", 4, "", nil},
			{"êutico", 4, "", nil},
			{"tico", 3, "", []string{
				"político", "eclesiástico", "diagnostico", "prático", "doméstico",
				"diagnóstico", "idêntico", "alopático", "artístico", "autêntico", "eclético", "crítico", "critico",
			}},
			{"ico", 4, "", []string{"tico", "público", "explico"}},
			{"ividade", 5, "", nil},
			{"idade", 4, "", []string{"autoridade", "comunidade"}},
			{"oria", 4, "", []string{"categoria"}},
			{"encial", 5, "", nil},
			{"ista", 4, "", nil},
			{"auta", 5, "", nil},
			{"quice", 4, "c", nil},
			{"ice", 4, "", []string{"cúmplice"}},
			{"íaco", 3, "", nil},
			{"ente", 4, "", []string{"freqüente", "alimente", "acrescente", "permanente", "oriente", "aparente"}},
			{"ense", 5, "", nil},
			{"inal", 3, "", nil},
			{"ano", 4, "", nil},
			{"ável", 2, "", []string{"afável", "razoável", "potável", "vulnerável"}},
			{"ível", 3, "", []string{"possível"}},
			{"vel", 5, "", []string{"possível", "vulnerável", "solúvel"}},
			{"bil", 3, "vel", nil},
			{"ura", 4, "", []string{"imatura", "acupuntura", "costura"}},
			{"ural", 4, "", nil},
			{"ual", 3, "", []string{"bissexual", "virtual", "visual", "pontual"}},
			{"ial", 3, "", nil},
			{"al", 4, "", []string{
				"afinal", "animal", "estatal", "bissexual", "desleal", "fiscal", "formal",
				"pessoal", "liberal", "postal", "virtual", "visual", "pontual", "sideral", "sucursal",
			}},
			{"alismo", 4, "", nil},
			{"ivismo", 4, "", nil},
			{"ismo", 3, "", []string{"cinismo"}},
		},
	},
	{
		Name:        Verbo,
		MinWordSize: 0,
		WithSuffix:  false,
		Suffixes:    nil,
		SubRules: []SubRule{
			{"aríamo", 2, "", nil},
			{"ássemo", 2, "", nil},
			{"eríamo", 2, "", nil},
			{"êssemo", 2, "", nil},
			{"iríamo", 3, "", nil},
			{"íssemo", 3, "", nil},
			{"áramo", 2, "", nil},
			{"árei", 2, "", nil},
			{"aremo", 2, "", nil},
			{"ariam", 2, "", nil},
			{"aríei", 2, "", nil},
			{"ássei", 2, "", nil},
			{"assem", 2, "", nil},
			{"ávamo", 2, "", nil},
			{"êramo", 3, "", nil},
			{"eremo", 3, "", nil},
			{"eriam", 3, "", nil},
			{"eríei", 3, "", nil},
			{"êssei", 3, "", nil},
			{"essem", 3, "", nil},
			{"íramo", 3, "", nil},
			{"iremo", 3, "", nil},
			{"iriam", 3, "", nil},
			{"iríei", 3, "", nil},
			{"íssei", 3, "", nil},
			{"issem", 3, "", nil},
			{"ando", 2, "", nil},
			{"endo", 3, "", nil},
			{"indo", 3, "", nil},
			{"ondo", 3, "", nil},
			{"aram", 2, "", nil},
			{"arão", 2, "", nil},
			{"arde", 2, "", nil},
			{"arei", 2, "", nil},
			{"aremo", 2, "", nil},
			{"aram", 2, "", nil},
			{"aria", 2, "", nil},
			{"armo", 2, "", nil},
			{"asse", 2, "", nil},
			{"aste", 2, "", nil},
			{"avam", 2, "", []string{"agravam"}},
			{"ávei", 2, "", nil},
			{"eram", 3, "", nil},
			{"erão", 3, "", nil},
			{"erde", 3, "", nil},
			{"erei", 3, "", nil},
			{"êrei", 3, "", nil},
			{"erem", 3, "", nil},
			{"eria", 3, "", nil},
			{"ermo", 3, "", nil},
			{"esse", 3, "", nil},
			{"este", 3, "", []string{"faroeste", "agreste"}},
			{"íamo", 3, "", nil},
			{"iram", 3, "", nil},
			{"íram", 3, "", nil},
			{"irão", 2, "", nil},
			{"irde", 2, "", nil},
			{"irei", 3, "", []string{"admirei"}},
			{"irem", 3, "", []string{"adquirem"}},
			{"iria", 3, "", nil},
			{"irmo", 3, "", nil},
			{"isse", 3, "", nil},
			{"iste", 4, "", nil},
			{"iava", 4, "", []string{"ampliava"}},
			{"amo", 2, "", nil},
			{"iona", 3, "", nil},
			{"ara", 2, "", []string{"arara", "prepara"}},
			{"ará", 2, "", []string{"alvará"}},
			{"are", 2, "", []string{"prepare"}},
			{"ava", 2, "", []string{"agrava"}},
			{"emo", 2, "", nil},
			{"era", 3, "", []string{"acelera", "espera"}},
			{"erá", 3, "", nil},
			{"ere", 3, "", []string{"espere"}},
			{"iam", 3, "", []string{"enfiam", "ampliam", "elogiam", "ensaiam"}},
			{"íei", 3, "", nil},
			{"imo", 3, "", []string{"reprimo", "intimo", "íntimo", "nimo", "queimo", "ximo"}},
			{"ira", 3, "", []string{"fronteira", "sátira"}},
			{"ído", 3, "", nil},
			{"irá", 3, "", nil},
			{"tizar", 4, "", []string{"alfabetizar"}},
			{"izar", 5, "", []string{"organizar"}},
			{"itar", 5, "", []string{"acreditar", "explicitar", "estreitar"}},
			{"ire", 3, "", []string{"adquire"}},
			{"omo", 3, "", nil},
			{"ai", 2, "", nil},
			{"am", 2, "", nil},
			{"ear", 4, "", []string{"alardear", "nuclear"}},
			{"ar", 2, "", []string{"azar", "bazaar", "patamar"}},
			{"uei", 3, "", nil},
			{"uía", 5, "u", nil},
			{"ei", 3, "", nil},
			{"guem", 3, "g", nil},
			{"em", 2, "", []string{"alem", "virgem"}},
			{"er", 2, "", []string{"éter", "pier"}},
			{"eu", 3, "", []string{"chapeu"}},
			{"ia", 3, "", []string{
				"estória", "fatia", "acia", "praia", "elogia", "mania", "lábia", "aprecia",
				"polícia", "arredia", "cheia", "ásia",
			}},
			{"ir", 3, "", []string{"freir"}},
			{"iu", 3, "", nil},
			{"eou", 5, "", nil},
			{"ou", 3, "", nil},
			{"i", 3, "", nil},
		},
	},
	{
		Name:        Vogal,
		MinWordSize: 0,
		WithSuffix:  true,
		Suffixes:    nil,
		SubRules: []SubRule{
			{"bil", 2, "vel", nil},
			{"gue", 2, "g", []string{"gangue", "jegue"}},
			{"á", 3, "", nil},
			{"ê", 3, "", []string{"bebê"}},
			{"a", 3, "", []string{"ásia"}},
			{"e", 3, "", nil},
			{"o", 3, "", []string{"ão"}},
		},
	},
}
